# -*- coding: utf-8 -*-
"""P3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9SgVS6HMvCQskOPOPozqMy2_d3PdHeK

#Project 3
Written by Cricket Bergner

Started: 3/10/26

Ended: 3/??/26
"""

# import and functions
################################################################################

# import libraries
import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import odeint, solve_ivp
from scipy.spatial import ConvexHull

# derivative functions (adjusted for damped and undamped)
def accel(x, v, omega, damping):
    return -omega**2*x - damping*v

def deriv_ivp(t, N, omega, damping):
    x, v = N
    dxdt = v
    dvdt = -omega**2*x - damping*v
    return [dxdt, dvdt]

def deriv_odeint(N, t, omega, damping):
    x, v = N
    dxdt = v
    dvdt = -omega**2*x - damping*v
    return [dxdt, dvdt]

# Scipy Method
def scipy_method(N_initial, tmin, tmax, nts, deriv):
    t = np.linspace(tmin, tmax, nts)
    N = odeint(deriv, N_initial, t)
    x = N[:,0]
    v = N[:,1]

    return t, x, v

# RK4(5) scipy function
def RK45_method(N_initial, tmin, tmax, nts, deriv):
  t = np.linspace(tmin, tmax, nts)
  sol = solve_ivp(deriv, (tmin, tmax), N_initial, method='RK45', t_eval=t)
  x = sol.y[0]
  v = sol.y[1]

  return t, x, v

# Verlet-velocity sympletic integrator functions
def verlet(N_initial, tmin, tmax, nts, deriv):

  # define inital variables
  x0, v0 = N_initial
  x = np.zeros(nts + 1)
  v = np.zeros(nts + 1)
  x[0] = x0
  v[0] = v0
  t = np.linspace(tmin, tmax, nts + 1)
  dt = t[1] - t[0]

  # loop
  for i in range(nts):
    a = deriv(x[i], v[i])
    v_half = v[i] + 0.5 * dt * a
    x[i+1] = x[i] + dt * v_half
    a_new = deriv(x[i+1], v_half)
    v[i+1] = v_half + 0.5 * dt * a_new

  return t, x, v

def psa(traj_list): # psa = phase space area
  nts = len(traj_list[0][0]) # length of the 2D array
  area = np.zeros(nts) # fill it with zeroes

  for i in range(nts): # loop through each time step
    pts = np.array([[t[0][i], t[1][i]] for t in traj_list]) # stack (x, v) for each particle
    hull = ConvexHull(pts) #calculates area
    area[i] = hull.volume # it says volume but really it is returning an area

  return area

def three_solvers(pts, omega, damping): # function to condense code
  straj, rtraj, vtraj = [], [], [] # short for scipy trajectories (undamped)
  straj_d, rtraj_d, vtraj_d = [], [], [] # damped

  for (x0,v0) in pts: # for every point in the 2D array
    st, sx, sv = scipy_method([x0, v0], tmin, tmax, nts, lambda N, t: deriv_odeint(N, t, omega, 0))
    straj.append((sx, sv))

    _, rx, rv = RK45_method([x0, v0], tmin, tmax, nts, lambda t, N: deriv_ivp(t, N, omega, 0))
    rtraj.append((rx, rv))

    _, vx, vv = verlet([x0, v0], tmin, tmax, nts, lambda x, v: accel(x, v, omega, 0))
    vtraj.append((vx, vv))

    _, sx_d, sv_d = scipy_method([x0, v0], tmin, tmax, nts, lambda N, t: deriv_odeint(N, t, omega, damped))
    straj_d.append((sx_d, sv_d))

    _, rx_d, rv_d = RK45_method([x0, v0], tmin, tmax, nts, lambda t, N: deriv_ivp(t, N, omega, damped))
    rtraj_d.append((rx_d, rv_d))

    _, vx_d, vv_d = verlet([x0, v0], tmin, tmax, nts, lambda x, v: accel(x, v, omega, damped))
    vtraj_d.append((vx_d, vv_d))

  return st, straj, rtraj, vtraj, straj_d, rtraj_d, vtraj_d

def jacobian(int_func, qn, pn, dt, epsilon=1e-6):
  q_next, p_next = int_func(qn, pn, dt) # get result for the timestep

  qq_next, pq_next = int_func(qn + epsilon, pn, dt) # get result for the nudged q
  dq = (np.array([qq_next, pq_next]) - np.array([q_next, p_next])) / epsilon # derivative of q

  qp_next, pp_next = int_func(qn, pn + epsilon, dt) # get result for the nudged p
  dp = (np.array([qp_next, pp_next]) - np.array([q_next, p_next])) / epsilon # derivative of p

  jacobian = np.column_stack((dq, dp)) # assemble the matrix

  return jacobian

def onestep_verlet(q, p, dt, omega, damping):
    a = -omega**2 * q - damping * p
    p_half = p + 0.5 * dt * a
    nq = q + dt * p_half
    na = -omega**2 * nq - damping * p_half
    np = p_half + 0.5 * dt * na

    return nq, np

################################################################################

# For a simple harmonic oscillator not at rest, what
# shape will it trace out in phase space?
################################################################################

# define initial variables
m = 1
k = 3
b = 0 # undamped
omega = np.sqrt(k/m)
damping = 0
nts = 1024 # larger nts, better approximation

N_initial = [1, 0]
tmin = 0
tmax = 10

# call the integrators
t_s, x_s, v_s = scipy_method(N_initial, tmin, tmax, nts, lambda N, t_odeint: deriv_odeint(N, t_odeint, omega, damping))
t_r, x_r, v_r = RK45_method(N_initial, tmin, tmax, nts, lambda t_ivp, N_ivp: deriv_ivp(t_ivp, N_ivp, omega, damping))
t_v, x_v, v_v = verlet(N_initial, tmin, tmax, nts, lambda x, v: accel(x, v, omega, damping))

# make the plots
plt.plot(v_r, x_r, color = '#f37fb0', label = "RK4", linewidth = 10)
plt.plot(v_v, x_v, 'o', color = '#61dbb0', label = "Verlet")
plt.plot(v_s, x_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Position (m)")
plt.title("Phase Space of a Harmonic Oscillator")
plt.legend()
plt.show()
print("")

print("The shape the simple harmonic oscillator will trace out in phase space is an ellipse. Note that all the integration methods were passed")
print("different initial variables. This shows even with different initial conditions the phase space will always show an ellipse.")
print("")

################################################################################
# How does a SHM evolve with a linear damping term?
################################################################################

# damping term added
damping = 0.2 / m

N_initial = [1, 0]
tmin = 0
tmax = 100

# call the integrators
nt_s, nx_s, nv_s = scipy_method(N_initial, tmin, tmax, nts, lambda N, t_odeint: deriv_odeint(N, t_odeint, omega, damping))
nt_r, nx_r, nv_r = RK45_method(N_initial, tmin, tmax, nts, lambda t_ivp, N_ivp: deriv_ivp(t_ivp, N_ivp, omega, damping))
nt_v, nx_v, nv_v = verlet(N_initial, tmin, tmax, nts, lambda x, v: accel(x, v, omega, damping))

# make the plots
plt.plot(nv_r, nx_r, 'o', color = '#f37fb0', label = "RK4", linewidth = 20)
plt.plot(nv_v, nx_v, color = '#61dbb0', label = "Verlet")
plt.plot(nv_s, nx_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Position (m)")
plt.title("Phase Space of a Harmonic Oscillator with Damping Term")
plt.legend()
plt.show()
print("")

print("The SHO evolves into a spiral.")
print("")

################################################################################
# How does the total mechanical energy (T+V) change over time with different
# solvers (see below) in these two cases?
################################################################################

# total mechanical energy
E_r = 0.5*m*v_r**2 + 0.5*k*x_r**2
E_v = 0.5*m*v_v**2 + 0.5*k*x_v**2
E_s = 0.5*m*v_s**2 + 0.5*k*x_s**2

nE_r = 0.5*m*nv_r**2 + 0.5*k*nx_r**2
nE_v = 0.5*m*nv_v**2 + 0.5*k*nx_v**2
nE_s = 0.5*m*nv_s**2 + 0.5*k*nx_s**2

# make the plots
plt.plot(t_r, E_r, color = '#f37fb0', label = "RK4")
plt.plot(t_v[:nts], E_v[:nts], color = '#61dbb0', label = "Verlet")
plt.plot(t_s, E_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Time (s)")
plt.ylabel("Energy (J)")
plt.title("Total Mechanical Energy Over Time")
plt.legend()
plt.show()
print("")

plt.plot(nt_r, nE_r, 'o', color = '#f37fb0', label = "RK4")
plt.plot(nt_v, nE_v, color = '#61dbb0', label = "Verlet")
plt.plot(nt_s, nE_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Time (s)")
plt.ylabel("Energy (J)")
plt.title("Total Mechanical Energy Over Time (Damped)")
plt.legend()
plt.show()
print("")

print("The total mechanical energy decreases over time for the oscillator, though it still oscillates around the origin.")
print("The total mechanical energy decreases over time for the damped oscillator, like a decaying exponential.")
print("")

"""Extension 1"""

# Symplectics Deep Dive: Programming
# Generate a method to calculate a phase space volume under time evolution.
# The fast way to accomplish this is with four points in (q,p) space and a method to calculate the area of their quadrilateral as a function of time.
# This will miss details as you go to longer time, because the shape may stop being rectangular.
# Instead, create a small meshgrid of (q,p) points and calculate the area of the concave hull that bounds those points.

# How does phase space area (Total Mechanical Energy) evolve in the damped and undamped SHM scenerios?
# How do different integrators affect this variation in area?

################################################################################

# set initial variables
delta = 0.1
damped = 0.2
mesh = [4, 16, 32] # first evolving over 4 points, then 16...

for Ngrid in mesh:

  x_pts = np.linspace(1 - delta, 1 + delta, Ngrid)
  v_pts = np.linspace(0 - delta, 0 + delta, Ngrid)
  pts = [(x, v) for x in x_pts for v in v_pts]

  t, straj, rtraj, vtraj, straj_d, rtraj_d, vtraj_d = three_solvers(pts, omega, damping)

  area_s = psa(straj)
  area_r = psa(rtraj)
  area_v = psa(vtraj)

  area_s_d = psa(straj_d)
  area_r_d = psa(rtraj_d)
  area_v_d = psa(vtraj_d)

  # plots
  print("")
  print("Plots for grid", Ngrid, "by", Ngrid)
  print("")
  plt.plot(t, area_s, color = 'red', label="Scipy")
  plt.plot(t, area_r, color = 'goldenrod', label="RK45")
  plt.plot(t, area_v[:len(t)], color = 'blue', label="Verlet")

  plt.xlabel("Time (s)")
  plt.ylabel("Phase Space Area (m^2)")
  plt.title("Undamped Osciallator")
  plt.legend()
  plt.show()
  print("")

  plt.plot(t, area_s_d, 'o', color = 'red', label="Scipy")
  plt.plot(t, area_r_d, color = 'green', label="RK45")
  plt.plot(t, area_v_d[:len(t)], '--', color = 'blue', label="Verlet")

  plt.xlabel("Time (s)")
  plt.ylabel("Phase Space Area (m^2)")
  plt.title("Damped Oscillator")
  plt.legend()
  plt.show()

"""Extension 2"""

# Symplectics Deep Dive: Calculation
# Similar to the LibreTexts derivation above, demonstrate that your higher order symplectic integrator conserves phase space.
################################################################################

print("For an undamped SHO, the phase space area should remain unchanged.")
print("")


def calculate_jacobian(integrator_func, qn, pn, dt, epsilon=1e-6):
    """
    Calculates the Jacobian matrix numerically for one time step.
    integrator_func should return (q_next, p_next) given (q, p, dt).
    """
    # 1. Get the baseline result
    q_next, p_next = integrator_func(qn, pn, dt)

    # 2. Nudge q and see how the output changes (dq_next/dq and dp_next/dq)
    q_nudge_q, p_nudge_q = integrator_func(qn + epsilon, pn, dt)
    deriv_wrt_q = (np.array([q_nudge_q, p_nudge_q]) - np.array([q_next, p_next])) / epsilon

    # 3. Nudge p and see how the output changes (dq_next/dp and dp_next/dp)
    q_nudge_p, p_nudge_p = integrator_func(qn, pn + epsilon, dt)
    deriv_wrt_p = (np.array([q_nudge_p, p_nudge_p]) - np.array([q_next, p_next])) / epsilon

    # Assemble the Jacobian matrix [[dq_next/dq, dq_next/dp], [dp_next/dq, dp_next/dp]]
    jacobian = np.column_stack((deriv_wrt_q, deriv_wrt_p))

    return jacobian

def verlet_step(q, p, dt, m=1.0, k=3.0):
    # Acceleration function: a = -k/m * q
    a = -(k/m) * q

    # Half step velocity
    p_half = p + 0.5 * a * dt

    # Full step position
    q_next = q + (p_half / m) * dt

    # New acceleration at new position
    a_next = -(k/m) * q_next

    # Full step velocity
    p_next = p_half + 0.5 * a_next * dt

    return q_next, p_next

# --- EXECUTION ---
qn, pn = 1.0, 2.0
dt = 0.1

J = calculate_jacobian(verlet_step, qn, pn, dt)
det = np.linalg.det(J)

print(f"Jacobian Matrix:\n{J}")
print(f"\nDeterminant: {det:.10f}")
print(f"Is it symplectic? {np.isclose(det, 1.0)}")

# Symplectics Deep Dive: Calculation
# Similar to the LibreTexts derivation above, demonstrate that your higher order symplectic integrator conserves phase space.
################################################################################

print("For an undamped SHO, the area should remain unchanged. We can test this by taking the determinant of the matrix.")
print("")

qn, pn = 1.0, 2.0
dt = 0.1

j = jacobian(lambda q, p, dt: verlet_step(q, p, dt, omega, damping), qn, pn, dt)
det = np.linalg.det(j)

print(f"Jacobian Matrix:\n{j}")
print("")
print(f"Determinant: {det:.10f}")
print("")
print("The determinant is one, thus, phase space area is conserved.")

